[package]
name = "stone"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[workspace]
members = [
    "components/collections/rb_tree",
    "components/collections/btree",
    "components/collections/range_tree",
    "components/sys",
    "components/spa",
]
